{% set name = "responsibleai-text" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/responsibleai_text-{{ version }}.tar.gz
  sha256: bdafb90de99ce713924185eda02b495bbc0cc4a74dbdd719a318b0813403128d

build:
  noarch: python
  script:
   - cp -R {{ RECIPE_DIR }}/requirements.txt {{ SRC_DIR }}/requirements.txt  # [unix]
   - echo f | xcopy /f /y /S %RECIPE_DIR%\requirements.txt %SRC_DIR%\requirements.txt  # [win]
   - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.17.2
    - pandas >=0.25.1
    - scikit-learn >=0.22.1
    - scipy >=1.4.1
    - semver >=2.13.0,<2.14.dev0
    - nlp-feature-extractors ==0.1.0
    - responsibleai >=0.32.1

test:
  imports:
    - responsibleai_text
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/responsible-ai-toolbox
  summary: SDK API to assess text Machine Learning models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
